### ISSUE TITLE
How to use with OpenHAB

### ISSUE THREAD

**Issue by srijken** [hobbyquaker/hmcon#28]
It seems that OpenHAB uses TclRegaScript for its RPC calls (see https://github.com/openhab/openhab/blob/master/bundles/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/client/CcuClient.java)

I'm using the Raspberry Pi module attached to GPIO. The HomeMatic web interface works, and I can control my devices with that.

There is some communication, because in the log I can see the Device ID of the Raspberry Pi CCU interface

```
2016-04-05 22:07:24.058 [INFO ] [.b.h.i.c.HomematicCommunicator] - Homematic ServerId[name=CCU,version=?,address=MEQ1...]
2016-04-05 22:07:24.071 [INFO ] [o.o.b.h.i.c.client.CcuClient  ] - Starting CcuClient
2016-04-05 22:07:24.204 [INFO ] [b.h.i.communicator.StateHolder] - Loading Homematic datapoints
2016-04-05 22:07:24.384 [ERROR] [.b.h.i.c.HomematicCommunicator] - Could not start Homematic communicator: Connection refused
org.openhab.binding.homematic.internal.communicator.client.HomematicClientException: Connection refused
    at org.openhab.binding.homematic.internal.communicator.client.CcuClient.sendScript(CcuClient.java:322) ~[bundlefile:na]
    at org.openhab.binding.homematic.internal.communicator.client.CcuClient.sendScriptByName(CcuClient.java:254) ~[bundlefile:na]
    at org.openhab.binding.homematic.internal.communicator.client.CcuClient.iterateAllDatapoints(CcuClient.java:126) ~[bundlefile:na]
    at org.openhab.binding.homematic.internal.communicator.StateHolder.loadDatapoints(StateHolder.java:84) ~[bundlefile:na]
    at org.openhab.binding.homematic.internal.communicator.HomematicCommunicator.start(HomematicCommunicator.java:93) ~[bundlefile:na]
    at org.openhab.binding.homematic.internal.bus.HomematicBinding.updated(HomematicBinding.java:95) [bundlefile:na]
```

Is there a way to make your installer work with OpenHAB and its HomeMatic binding?

**Comment by hobbyquaker** [comment]
I must admit that I don't really know if Openhab's Homematic Binding can work without the "Rega". But since the Binding supports Homegear I think it should be possible, because (afaik) Homegear also doesn't have the "Rega". I guess we should ask the Developer of Openhab's Homematic Binding if and how this is possible. If it's really not possible I will have to remove Openhab references in the Hmcon Readme.

**Comment by hobbyquaker** [comment]
I did some research and I fear this won't work :-(
see https://groups.google.com/forum/#!topic/openhab/DIK9wb0lTi4
Since OpenHAB 1.5 the Homematic Binding requires the Rega. Bummer! I can't understand why the OpenHAB guys made this decision,. The "Rega" is terribly unreliable and a kinda useless piece of Software if you have your "Logic Layer" in another Software anyway. 

So I see following possible actions for you now:
- Use Homegear instead of Hmcon. Homegear has special extensions that make it work with OpenHAB's Homematic Binding. Drawback: most likely Homegear will never support Homematic-IP devices, Hmcon will do in future very probably.
- Use "LXCCU" instead of Hmcon. Drawback: Not 100% stable (imho), not supporting the newest devices (until now it's based on the 2.15 CCU Firmware), really terrible Interface, it's a pain in the arse to manage your devices with this, especially when you have many devices... It's the same Software that runs on a CCU - including the "Rega".
- Buy a CCU - same drawbacks as LXCCU above (except device support) and the CCU has a very old CPU, so it's very slow also.
- Get in contact with the OpenHAB guys and ask them if they see any possibility to change the Homematic Binding so it will work without a Rega.
- Use e.g. mqtt-smarthome, ioBroker or IP-Symcon instead of OpenHAB.

My personal suggestion would be the last point. YMMV.

**Comment by hobbyquaker** [comment]
the developer of the homematic binding told me that it will be possible with openhab 2 again. so there is another possibility for you now: wait for openhab 2 :-)

**Comment by srijken** [comment]
I'm also looking into mqtt-smarthome right now. Got it more or less working. The nice thing about OpenHab is that it's easy to create a smartphone app to control things.
Next step I'm going to try is connecting OpenHab to MQTT and control things that way
